### PR TITLE
Set _updatingReadonlyProperty on _rerender, fixes #6

### LINKED ISSUE #6: Computed properties break _rerender
When a component uses computed properties, `_rerender` tries to `set()` those, which makes `_checkReadOnly` inside the component throw. This leads to a full reload when using svelte-loader with hotReload.

I couldn't find way to tell if a property is computed, though a possible workaround seems to be replacing [this line](https://github.com/ekhaled/svelte-dev-helper/blob/560b85517ac737a0011ff5fee29f15ee34c5abd7/lib/proxy.js#L201) with
```
  this.proxyTarget._updatingReadonlyProperty = true;
  this.set(oldstate);
  this.proxyTarget._updatingReadonlyProperty = false;
```

Although that feels somewhat dirty. What do you think?

### PR DESCRIPTION
**Pull request by aphitiel**
For the test I had to include svelte, is that ok?

### CODE REVIEW

**Comment by ekhaled** [comment]
Thanks a lot for the PR and the bug report.
merged and released in `v1.1.6`
I just removed the dependency on svelte and used a mock component instead

**Comment by aphitiel** [comment]
Sorry for not explaining - the idea behind including svelte was that when/if _updatingReadonlyProperty got refactored in svelte, the test would fail and remind us of our deeds;)

But what's worse: I just realised that changes to the computed property itself won't be applied with this approach. And I can't seem to find a way to force them to recalculate.

So it might be less confusing to just let the HMR fail and do a full reload until we can find a way to distinguish computeds.

One possibility would be to set each item of oldstate by itself, wrapped in a try-catch. That would remove the dependency on _updatingReadonlyProperty, but be a bit slower. And ugly, too.

**Comment by ekhaled** [comment]
I spoke to Rich about the possibility of refactoring _updatingReadonlyProperty.
Nothing is planned for now, but we have plans for transplanting this helper directly into svelte core. 

For now this hack will be ok. 

As for recalculation. Does calling  this.proxyTarget._recompute after calling set()  help?

**Comment by ekhaled** [comment]
With preserving state, there is already a caveat. 
If you change data initial values, that doesn't get reflected on hot reload anyway.

So maybe we can live with this too?

**Comment by aphitiel** [comment]
Couldn't get _recompute to work, sadly. Tried variations along the lines of ..._recompute(oldstate, this.get()) but that led to strange things.

The problem with applying the state preserving caveat to computeds is that they **will** recalculate when their dependencies change after rerender. So they don't exactly stay in the initial state.

**Comment by ekhaled** [comment]
Now that the error is not triggered anymore... 
Can you do me a minimal repro of a component so I can check on my side please.
Please list whats expected to happen and what you see happening. 

Thanks

**Comment by aphitiel** [comment]
Repro: https://github.com/aphitiel/svelte-computed-hmr, hope this works:

`# npm install && npm run dev`

1. Initially, it shows
```
computed: 10
a: 1
```

2. Edit `Component.html`:
`test: a => a * 10,`
 to
`test: a => a * 100,`

3. HMR updates, it still shows
```
computed: 10
a: 1
```
-> It should have updated `computed` to `100`, IMHO

4. Click `++`, now it shows
```
computed: 200
a: 2
```

PS: If you click ++ before the first edit, it will update at step 3.

**Comment by ekhaled** [comment]
A REPL would have sufficient. 
But, Thank you very much for going to that length.

Let me have a poke and get back to you

**Pull request merged**
