### PR TITLE
Add _bind to forwardedMethods; fixes sveltejs/svelte-loader#46

### LINKED ISSUE #46: hotReload does not like bound properties
When hotReload is enabled and component contains a bound property, it sadly throws `TypeError: xxx._bind is not a function.`

Simplest reproduction would be a new [sapper-template](https://github.com/sveltejs/sapper-template), and  adding e.g. `bind:value` to the `<Layout` component in routes/index.html:
`<Layout bind:value page='home'>`

### PR DESCRIPTION
**Pull request by aphitiel**
Hi, this fixes sveltejs/svelte-loader#46. HMR rocks, thanks!

### CODE REVIEW

**Comment by ekhaled** [comment]
Thank you!
Dunno how I missed `_bind`.

Can you please update `allMethods` and `straightProxiedMethods` [here](https://github.com/ekhaled/svelte-dev-helper/blob/master/test/proxy.spec.js#L37-L38) so that this is tested for in the future

thanks

Edit: and `proxiedMethods`

**Comment by aphitiel** [comment]
Oops, I thought "tests!" right after submitting the PR, but you were too quick;)

While wondering why I couldn't make the test fail I noticed that `createProxy` adds the mock-methods outside of the constructor as custom methods. So I put the mock for `_bind` inside the constructor.

But that means that the test would not detect if other members of `allMethods` were missing in `createProxy` - remove `_recompute` from `allMethods` and the tests will still pass. Or am I missing something?

**Comment by ekhaled** [comment]
Thanks,
The tests are a bit tricky.... 
We are proxying a class without thouching any of it's prototype. It may have methods and properties that we are unaware of, which is fine. 
We are just testing that the methods that we **are** forwarding/handling does actually end up calling their repective targets

**Comment by ekhaled** [comment]
Thanks @aphitiel released `1.1.5`.
Doing a `npm update` should pick up the changes here as well as the changes @Rich-Harris just released in svelte-loader

**Pull request merged**
