### PR TITLE
fixes #8

### LINKED ISSUE #8: Follow up to #7
After fixing #6 with #7 
There is still an outstanding issue (see #7 for more info and a reproduction).

If computed props were never computed before, they don't update after an HMR update.
However, if they were computed even once... they do update.

This is when you change the function that does the computation.

### PR DESCRIPTION
**Pull request by ekhaled**
@aphitiel can you check this branch against your codebase and see if you can find any problems please.

AFAICT this looks good for all of my codebases

### CODE REVIEW

**Comment by aphitiel** [comment]
Actually, yes, found something. Really sorry about that. Updated repro with [here](https://github.com/aphitiel/svelte-computed-hmr/commit/6ea6d25a863a25cb6423d69457fd2c4a8f38b78e).

Now, when you change the computed, it will correctly update; but after the timeout on oncreate, it will revert back to the old computed. Until you press the button...

**Comment by ekhaled** [comment]
sure looks contrived, but even if we don't use a `setTimeout` and change the value using a button, the same behaviour is present.

Try now please

**Comment by aphitiel** [comment]
Yay! That did it, thank you so much!

**Comment by ekhaled** [comment]
No. Thank **You**

Released in v1.1.7

**Pull request merged**
